### ISSUE TITLE
Fix variable processing in `href` field in `toc.yaml`

### ISSUE THREAD

**Issue by iglunchadze** [diplodoc-platform/diplodoc#12]
This works fine:

```yaml
title: Test document
items:
  - name: Index
    href: index.md
  - name: External article
    href: https://example.com
```

But when you create a variable for the URL, `url: https://example.com`, and use it in the `href` value, there's an error:

```yaml
title: Test document
items:
  - name: Index
    href: index.md
  - name: External article
    href: "{{ url }}"
```

```
No such file or has no access to /home/glunchadze/diplodoc-test-gen/.tmp_input/{{ url }}.md Error: ENOENT: no such file or directory, open '/home/glunchadze/diplodoc-test-gen/.tmp_input/{{ url }}.md'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at /home/glunchadze/.nvm/versions/node/v18.18.2/lib/node_modules/@diplodoc/cli/build/index.js:2140:49
    at Generator.next (<anonymous>)
    at /home/glunchadze/.nvm/versions/node/v18.18.2/lib/node_modules/@diplodoc/cli/build/index.js:78:61
    at new Promise (<anonymous>)
    at __async (/home/glunchadze/.nvm/versions/node/v18.18.2/lib/node_modules/@diplodoc/cli/build/index.js:62:10)
    at resolveMd2HTML (/home/glunchadze/.nvm/versions/node/v18.18.2/lib/node_modules/@diplodoc/cli/build/index.js:2130:10)
    at /home/glunchadze/.nvm/versions/node/v18.18.2/lib/node_modules/@diplodoc/cli/build/index.js:2969:12
    at Generator.next (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/glunchadze/diplodoc-test-gen/.tmp_input/{{ url }}.md'
}

ERR No such file or has no access to /{{ url }}.md
```
