### ISSUE TITLE
Absolute path in assets

### ISSUE THREAD

**Issue by kirillde** [diplodoc-platform/diplodoc#16]
I have .md file:

```
# Описание папок в src и проектов в них

В папке **src** находится исходный код микросервисов, модулей и вспомогательных библиотек ... .

![](../_images/structure.png)

## Extras

Папка, cодержащая вспомогательные библиотеки, используемые для поддержки мультиязычности в библиотеках вьювера.

...... - фронтэнд библиотека для сбора локалей и поддержки мультиязычности в библиотеках вьювера.

## Tangl

Содержит библиотеки вьювера.

### Вьювер

- ......  - библиотека вьювера.
```

and toc.yaml file

```
title: ....
href: index.yaml;
navigation:
  logo:
    url: '../tangl'
  header:
    leftItems:
      - text: 'Item..'
        type: 'link'
        #url: '../../how-to/'
      - text: 'Item...'
        type: 'link'
        #url: '../../docs/ru/'
items:
  - name: CHANGELOG
    href: CHANGELOG.md
  - name: Разделы
    expanded: true
    items:
      - name: Структура
        href: structure.md
```

run this command ` yfm -i ./docs -o ./output`

and i have generated object with assets, which has absolute path for images in assets list

`{
  "data": {
    "leading": false,
    "toc": {
      "title": "Tangl",
      "href": "index.html",
      "navigation": {
        "logo": {
          "url": "../tangl"
        },
        "header": {
          "leftItems": [
            {
              "text": "Item..",
              "type": "link"
            },
            {
              "text": "Item...",
              "type": "link"
            }
          ]
        }
      },
      "items": [
        {
          .....
        },
        {
          .....
        },
        {
          "name": "Разделы",
          "expanded": true,
          "items": [
            ......
          ],
          "id": "Разделы-2-0.2943391760813012"
        }
      ],
      "base": "...."
    },
    "meta": {
      "metadata": [],
      "style": [],
      "script": []
    },
    "assets": [
      "/home/..../www/work/test/output/.tmp_input/_images/structure.png"
    ],
    "headings": [
      {
        "title": "Extras",
        "href": "#extras",
        "level": 2
      },
      {
        "title": "....",
        "href": "#...",
        "level": 2,
        "items": [
          {
            "title": "Вьювер",
            "href": "#vyuver",
            "level": 3
          }
        ]
      }
    ],
    "title": "Описание папок в src и проектов в них",
    "includes": [],
    "html": "...."
  },
  "router": {
    "pathname": "structure.html"
  }
}`

I expect relative path and can assume this tmp folders shouldn't exist in list

But... my html generated correctly `<img src="../_images/tangl-structure.png" />`
