### ISSUE TITLE
YFM render error

### ISSUE THREAD

**Issue by Alegr37** [diplodoc-platform/diplodoc#31]
Seems like render order error

Minimal repro, presets.yaml:
```yaml
default:
  test:
    t: 1
    # testarray: [1]
```

test.md:
```liquid
{% if test.testarray %}
{% for testval in test.testarray %}
  - {{ testval }}
{% endfor %}
{% endif %}
```

```bash
$ yfm -i ./ -o ~/render
```

leads to:
```bash
ERR  test.testarray is undefined or not iterable
```
